# Generated by Django 4.0 on 2021-12-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='bla', upload_to='Images/'),
            preserve_default=False,
        ),
    ]
