# Generated by Django 4.0 on 2021-12-20 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
